// Auto-generated by version_gen.py — do not edit manually
#pragma once

namespace hb::version
{

namespace compatibility
{
constexpr int major = 0;
constexpr int minor = 2;
constexpr int patch = 9;
constexpr int build_number = 0;
constexpr const char* stage = "alpha";
constexpr const char* display_version = "0.2.9-alpha";
constexpr const char* full_version = "0.2.9-alpha+build.0";
} // namespace compatibility

namespace server
{
constexpr int major = 0;
constexpr int minor = 1;
constexpr int patch = 13;
constexpr int build_number = 93;
constexpr const char* stage = "alpha";
constexpr const char* display_version = "0.1.13-alpha";
constexpr const char* full_version = "0.1.13-alpha+build.93";
} // namespace server

namespace client
{
constexpr int major = 0;
constexpr int minor = 2;
constexpr int patch = 15;
constexpr int build_number = 101;
constexpr const char* stage = "alpha";
constexpr const char* display_version = "0.2.15-alpha";
constexpr const char* full_version = "0.2.15-alpha+build.101";
} // namespace client

constexpr const char* build_timestamp = "2026-02-19T10:34:12";

} // namespace hb::version
