// Auto-generated by version_gen.py — do not edit manually
#pragma once

namespace hb::version
{

namespace compatibility
{
constexpr int major = 0;
constexpr int minor = 2;
constexpr int patch = 2;
constexpr const char* stage = "alpha";
constexpr const char* display_version = "0.2.2-alpha";
constexpr const char* full_version = "0.2.2-alpha+build.62";
} // namespace compatibility

namespace server
{
constexpr int major = 0;
constexpr int minor = 1;
constexpr int patch = 2;
constexpr const char* stage = "alpha";
constexpr const char* display_version = "0.1.2-alpha";
constexpr const char* full_version = "0.1.2-alpha+build.62";
} // namespace server

namespace client
{
constexpr int major = 0;
constexpr int minor = 2;
constexpr int patch = 2;
constexpr const char* stage = "alpha";
constexpr const char* display_version = "0.2.2-alpha";
constexpr const char* full_version = "0.2.2-alpha+build.62";
} // namespace client

constexpr int build_number = 62;
constexpr const char* build_timestamp = "2026-02-17T02:59:03";

} // namespace hb::version
